services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: nhtravels
      POSTGRES_USER: nhtravels
      POSTGRES_PASSWORD: nhtravels
    ports:
      - "5432:5432"
    volumes:
      - nh_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
volumes:
  nh_postgres_data:
