# Generated manually for the NH Travels backend.
from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="Bus", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("name", models.CharField(default="NH Travels", max_length=120)),
            ("model", models.CharField(default="Eicher Skyline", max_length=120)),
            ("registration_number", models.CharField(max_length=30, unique=True)),
            ("bus_type", models.CharField(default="AC Semi-Sleeper", max_length=50)),
            ("total_seats", models.PositiveIntegerField(default=40)),
            ("active", models.BooleanField(default=True)),
            ("amenities", models.JSONField(blank=True, default=list)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
        ]),
        migrations.CreateModel(name="Route", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("name", models.CharField(max_length=150)),
            ("code", models.CharField(max_length=30, unique=True)),
            ("active", models.BooleanField(default=True)),
        ]),
        migrations.CreateModel(name="Stop", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("city", models.CharField(choices=[("GORAKHPUR", "Gorakhpur"), ("AYODHYA", "Ayodhya"), ("LUCKNOW", "Lucknow"), ("KANPUR", "Kanpur")], max_length=30)),
            ("sequence", models.PositiveIntegerField()),
            ("arrival_time", models.TimeField(blank=True, null=True)),
            ("departure_time", models.TimeField(blank=True, null=True)),
            ("next_day", models.BooleanField(default=False)),
            ("address", models.CharField(blank=True, max_length=255)),
            ("route", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stops", to="booking.route")),
        ], options={"ordering":["sequence"]}),
        migrations.CreateModel(name="BusSeat", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("number", models.CharField(max_length=10)),
            ("row", models.PositiveIntegerField()),
            ("column", models.CharField(max_length=2)),
            ("seat_type", models.CharField(default="SEMI_SLEEPER", max_length=50)),
            ("active", models.BooleanField(default=True)),
            ("bus", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="seats", to="booking.bus")),
        ]),
        migrations.CreateModel(name="RouteFare", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ("from_stop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="departure_fares", to="booking.stop")),
            ("route", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fares", to="booking.route")),
            ("to_stop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="arrival_fares", to="booking.stop")),
        ]),
        migrations.CreateModel(name="Trip", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("travel_date", models.DateField()),
            ("direction", models.CharField(choices=[("OUTBOUND", "Gorakhpur → Kanpur"), ("RETURN", "Kanpur → Gorakhpur")], max_length=20)),
            ("active", models.BooleanField(default=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("bus", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="trips", to="booking.bus")),
            ("route", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="trips", to="booking.route")),
        ], options={"ordering":["travel_date", "direction"]}),
        migrations.CreateModel(name="TripSeat", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("seat", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="trip_seats", to="booking.busseat")),
            ("trip", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="trip_seats", to="booking.trip")),
        ]),
        migrations.CreateModel(name="Customer", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("name", models.CharField(max_length=150)),
            ("phone", models.CharField(max_length=20)),
            ("email", models.EmailField(max_length=254)),
            ("sex", models.CharField(max_length=20)),
            ("age", models.PositiveIntegerField(blank=True, null=True)),
            ("alternate_phone", models.CharField(blank=True, max_length=20)),
            ("notes", models.TextField(blank=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
        ]),
        migrations.CreateModel(name="Booking", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("reference", models.CharField(editable=False, max_length=20, unique=True)),
            ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ("status", models.CharField(choices=[("PAYMENT_PENDING", "Payment pending"), ("CONFIRMED", "Confirmed"), ("CANCELLED", "Cancelled"), ("EXPIRED", "Expired"), ("REFUNDED", "Refunded")], default="PAYMENT_PENDING", max_length=30)),
            ("payment_method", models.CharField(blank=True, max_length=30)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ("boarding_stop", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="boarding_bookings", to="booking.stop")),
            ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bookings", to="booking.customer")),
            ("dropping_stop", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="dropping_bookings", to="booking.stop")),
            ("trip", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bookings", to="booking.trip")),
        ]),
        migrations.CreateModel(name="BookingSeat", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("boarding_sequence", models.PositiveIntegerField()),
            ("dropping_sequence", models.PositiveIntegerField()),
            ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ("booking", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="seats", to="booking.booking")),
            ("trip_seat", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="booking_seats", to="booking.tripseat")),
        ]),
        migrations.CreateModel(name="SeatHold", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("token", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
            ("boarding_sequence", models.PositiveIntegerField()),
            ("dropping_sequence", models.PositiveIntegerField()),
            ("expires_at", models.DateTimeField()),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("trip", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="holds", to="booking.trip")),
            ("trip_seat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="holds", to="booking.tripseat")),
        ]),
        migrations.CreateModel(name="Payment", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("gateway", models.CharField(default="DEMO", max_length=30)),
            ("gateway_order_id", models.CharField(blank=True, max_length=100)),
            ("gateway_payment_id", models.CharField(blank=True, max_length=100)),
            ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ("status", models.CharField(choices=[("CREATED", "Created"), ("SUCCESS", "Success"), ("FAILED", "Failed"), ("REFUNDED", "Refunded")], default="CREATED", max_length=20)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("paid_at", models.DateTimeField(blank=True, null=True)),
            ("booking", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="payment", to="booking.booking")),
        ]),
        migrations.AddConstraint(model_name="stop", constraint=models.UniqueConstraint(fields=("route", "sequence"), name="uniq_route_sequence")),
        migrations.AddConstraint(model_name="stop", constraint=models.UniqueConstraint(fields=("route", "city"), name="uniq_route_city")),
        migrations.AddConstraint(model_name="busseat", constraint=models.UniqueConstraint(fields=("bus", "number"), name="uniq_bus_seat")),
        migrations.AddConstraint(model_name="routefare", constraint=models.UniqueConstraint(fields=("route", "from_stop", "to_stop"), name="uniq_route_fare")),
        migrations.AddConstraint(model_name="trip", constraint=models.UniqueConstraint(fields=("bus", "travel_date", "direction"), name="uniq_daily_trip")),
        migrations.AddConstraint(model_name="tripseat", constraint=models.UniqueConstraint(fields=("trip", "seat"), name="uniq_trip_seat")),
    ]
